### PR TITLE
Added 2048 game

### PR DESCRIPTION
**Pull request by jayg2309**
A simple implementation of 2048 game

### CODE REVIEW

**Comment by jayg2309** [comment]
@imharshtiwari Can you please add the 'hacktoberfest' label so this PR can be accepted in Hacktoberfest

**Comment by imharshtiwari** [comment]
Hai Jay
I have already assigned the suitable label

**Comment by jayg2309** [comment]
@imharshtiwari It's showing that my PR is excluded because your repository is excluded from Hacktoberfest. Can you please check?

**Comment by imharshtiwari** [comment]
I'm sorry ...I you are facing this issue.
Someone has reported this repo. As disobedience for following rules.
This repo is reported to completing the PR goals.

**Pull request merged**
