### PR TITLE
Dice Roller

### PR DESCRIPTION
**Pull request by Bhumitg07205**
Whenever the user refreshes the webpage, the dice will change. Each time a player will win. This allows users to play games that require dice.

### CODE REVIEW

**Comment by Bhumitg07205** [comment]
please tag me hacktoberfest accepted 
nothing is shown on my profile till yet 
regards 
Bhumit Gupta

**Comment by imharshtiwari** [comment]
Hai Bhumit ,
Firstly thank you for your contribution
Here no need to add tag for any hacktober fest.
You can easily track your PR on hacktober fest  dashboard.
It will take one week from the hacktober's site to reflect your successful
PR's

(Feel free to ask any doubt related to this )

Thank you

**Comment by Bhumitg07205** [comment]
Hey [imharshtiwari],

I hope you're doing well. I'm reaching out to you again regarding my first experience with Hacktoberfest. I don't have much knowledge about it, but I remember you mentioning that the "accepted" tag isn't necessary. However, without that tag, the timer doesn't appear on my profile. Here's a screenshot for reference: !
[Screenshot 2024-10-10 093014](https://github.com/user-attachments/assets/ddabe90d-d998-4517-aabd-cc3a36bedf25). Could you please explain this to me?

Thank you so much,
Bhumit Gupta

**Comment by Bhumitg07205** [comment]
image

**Comment by imharshtiwari** [comment]
Apology for Repository Contribution Issue

Dear [Bhumitg07205],

I hope this message finds you well. I am reaching out to sincerely
apologize for the recent issue with your contribution to my GitHub
repository, which unfortunately was not accepted by Hacktoberfest due to an
oversight on my part. The necessary tags and license were not properly
mentioned as required, resulting in the rejection of your contribution by
the bot.

I deeply regret this mistake and want to express my heartfelt apologies for
any inconvenience or disappointment this may have caused you. Your
contribution was valuable, and I truly appreciate the time and effort you
put into it.

I have taken immediate steps to rectify the oversight, and I am committed
to ensuring that such errors do not occur in the future. Your contribution
is important to me, and I would be grateful for another opportunity to
include it in the repository correctly.

Once again, I apologize for any inconvenience and thank you for your
understanding. Your support means a lot to me, and I hope we can continue
collaborating in the future.

Thank you for your understanding.

Warm regards,

**Comment by Bhumitg07205** [comment]
It's totally fine; we all make mistakes and learn from them. I would be happy to work with you in the future. Thank you so much for guiding me till now. - Bhumit

**Comment by imharshtiwari** [comment]
Thank you Bhumit for understanding me
And please update me whether your PR is showing (progress) on Hacktober
Dashboard or not.

**Comment by Bhumitg07205** [comment]
image
its the same

**Comment by imharshtiwari** [comment]
It will take about 3-4 hrs to update on hacktober Dashboard
Once update please inform me if not then I'll contact with maintainers

**Comment by Bhumitg07205** [comment]
image
it has been 4 hours sir

**Pull request merged**
